# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(blank=True, max_length=255)),
                ('bg_image', models.ImageField(blank=True, upload_to='panels')),
                ('id_target', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('content_secondary', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('media_panel_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commons_page_panel', to='commons.MediaPanel')),
                ('media_panels', models.ManyToManyField(blank=True, related_name='commons_page_panels', to='commons.MediaPanel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mediapanel',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='commons.Quote'),
        ),
    ]
