# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_category_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapanel',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='page',
            name='media_panel_default',
        ),
        migrations.RemoveField(
            model_name='page',
            name='media_panels',
        ),
        migrations.DeleteModel(
            name='MediaPanel',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
