# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_job_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2016, 4, 25), verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='init_date',
            field=models.DateField(blank=True, default=datetime.date(2016, 4, 25), verbose_name='Start Date'),
        ),
    ]
