# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-15 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0009_auto_20160926_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cc_myself',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
